# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node runtime as a parent image
FROM node:20-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Build the TypeScript application
RUN npm run build

# Use a smaller Node.js runtime image for the final build
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy the compiled JavaScript files and package.json
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package*.json /app/

# Install only production dependencies
RUN npm install --omit=dev

# Set the command to run the application
ENTRYPOINT ["node", "build/index.js"]